
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/picture_auth?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  flyway:
    enabled: true
    out-of-order: false
    encoding: utf-8
    placeholder-replacement: false
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  application:
    name: mx-security-auth




logging:
  level:
    org:
      springframework:
        security: trace
        web: ERROR
server:
  port: 8088
